import {
  activeProjects,
  legacyProjects,
  type FeatureColumn,
  type Project,
  type ProjectData,
  type VerifiedCell,
} from "./data.ts";
import type { CandidateData } from "./candidate-data.ts";

function link(label: string, source: string) {
  return `[${label}](${source})`;
}

function cellLabel(value: VerifiedCell["value"]) {
  if (value === true) return "Yes";
  if (value === false) return "No";
  if (value === null || value === "unknown") return "Unknown";
  return String(value);
}

function cell(value: VerifiedCell) {
  return link(cellLabel(value.value), value.source);
}

function factVerifiedAt(project: Project) {
  return [
    project.status,
    project.maturity,
    project.license.server,
    project.license.clients,
    project.data_source,
    ...Object.values(project.features),
  ]
    .map((entry) => entry.verified_at)
    .toSorted()
    .at(0)!;
}

function projectLink(project: Project) {
  return link(project.name, project.website);
}

function activeProjectCell(project: Project) {
  const repositoryUrl = `https://github.com/${project.repository}`;
  return project.website.replace(/\/$/, "") === repositoryUrl
    ? project.name
    : projectLink(project);
}

function lastCommitCell(project: Project) {
  return project.metrics.last_commit.value
    ? cell({
        ...project.metrics.last_commit,
        value: project.metrics.last_commit.value.slice(0, 10),
      })
    : cell(project.metrics.last_commit);
}

function legacyReason(project: Project) {
  if (project.metrics.archived.value === true) {
    return link("Repository archived", project.metrics.archived.source);
  }
  return link("Maintainer legacy disclaimer", project.status.source);
}

function activeRow(
  project: Project,
  featureColumns: FeatureColumn[],
  showFactsVerified: boolean,
) {
  const values = [
    activeProjectCell(project),
    link(project.repository, `https://github.com/${project.repository}`),
    cell(project.metrics.stars),
    cell(project.data_source),
    ...featureColumns.map((column) => cell(project.features[column.key]!)),
    lastCommitCell(project),
    cell(project.license.server),
    cell(project.license.clients),
    cell(project.maturity),
  ];
  if (showFactsVerified) values.push(factVerifiedAt(project));
  return values.join(" | ");
}

function interfaceNavigation(
  projects: Project[],
  featureColumns: FeatureColumn[],
) {
  return featureColumns
    .map((column) => {
      const matches = projects.filter(
        (project) => project.features[column.key]?.value === true,
      );
      const values =
        matches.length === 0
          ? "None in the current table"
          : matches.map(projectLink).join(", ");
      return `- **${column.navigation_label}:** ${values}`;
    })
    .join("\n");
}

export function renderReadme(data: ProjectData, _candidates: CandidateData) {
  const active = activeProjects(data);
  const legacy = legacyProjects(data);
  const featureColumns = data.comparison.feature_columns;
  const featureHeaders = featureColumns.map((column) => column.label);
  const factDates = active.map(factVerifiedAt);
  const showFactsVerified = new Set(factDates).size > 1;
  const headers = [
    "Project",
    "Repository",
    "Stars",
    "Data source",
    ...featureHeaders,
    "Last commit",
    "Server license",
    "Client license",
    "Maturity",
    ...(showFactsVerified ? ["Facts verified"] : []),
  ];
  const separators = headers.map((header) =>
    header === "Stars" ? "---:" : "---",
  );
  const metricsVerifiedAt = data.projects
    .flatMap((project) => [
      project.metrics.stars.verified_at,
      project.metrics.last_commit.verified_at,
      project.metrics.archived.verified_at,
      project.metrics.created_at.verified_at,
      project.metrics.latest_release.verified_at,
      project.maturity.verified_at,
    ])
    .toSorted()
    .at(-1);

  return `<!-- Generated by scripts/generate-readme.ts from projects.yml and candidates.yml. Do not edit by hand. -->

# ${data.comparison.title}

A maintained comparison of open-source, self-hosted SEO rank trackers -
features, licenses, data sources, and project health.

${data.comparison.disclosure} Placement cannot be purchased.

## Active projects

Projects are sorted by current GitHub stars, descending, with the project name
as the deterministic tie-breaker.

Every comparison cell links to public evidence. \`Unknown\` means the capability
was not documented in the project's complete declared public evidence set; it
does not mean the capability is absent.

| ${headers.join(" | ")} |
| ${separators.join(" | ")} |
${active
  .map(
    (project) =>
      `| ${activeRow(project, featureColumns, showFactsVerified)} |`,
  )
  .join("\n")}

\`BYOK\` means bring your own key: you connect credentials for your own data
provider account, and provider usage is billed separately.

${showFactsVerified ? "" : `**Facts verified:** ${data.comparison.verified_at}\n\n`}Metrics refreshed weekly. Last change: ${metricsVerifiedAt}.

### Browse by interface

${interfaceNavigation(active, featureColumns)}

See the complete reviewed [evidence](EVIDENCE.md) and the separately citable
[methodology](METHODOLOGY.md).

## Inclusion criteria

A candidate must publish open-source code, collect and retain website positions
in search results, provide a usable application, and document a public
self-hosting path.

\`Included\` is the category decision, while \`table-ready\` means enough public
evidence exists to publish a complete row. Only table-ready projects appear
above.

## Legacy projects

| Project | Why legacy | Last commit |
| --- | --- | --- |
${legacy
  .map(
    (project) =>
      `| ${projectLink(project)} | ${legacyReason(project)} | ${lastCommitCell(project)} |`,
  )
  .join("\n")}

## Related lists

${data.comparison.related_lists
  .map(
    (related) =>
      `- [${related.name}](${related.fact.source}): ${related.fact.value}. Verified ${related.fact.verified_at}.`,
  )
  .join("\n")}

## FAQ

### Why does Bisibility use AGPL-3.0?

Bisibility is licensed under AGPL-3.0; if you modify it and let users interact
with that version over a network, you must offer those users the corresponding
source. Self-hosting for your own use, including internally, does not trigger
that requirement.

### How can I correct a row?

Listed project maintainers can correct their row by opening an issue or pull
request. Corrections need a public source, and the same evidence rules apply to
every project. See [CONTRIBUTING.md](CONTRIBUTING.md).

## License

The factual data in \`projects.yml\` and \`candidates.yml\`, and the generated
comparison files are licensed under [CC BY 4.0](LICENSE). The TypeScript
programs in \`scripts/\` are licensed under
[Apache-2.0](scripts/LICENSE).
`;
}
