import {
  activeProjects,
  type FeatureColumn,
  type Project,
  type ProjectData,
} from "./data.ts";

function link(label: string, source: string) {
  return `[${label}](${source})`;
}

function evidenceNotes(projects: Project[], featureColumns: FeatureColumn[]) {
  const notes: string[] = [];
  for (const project of projects) {
    if (project.license.server.note) {
      notes.push(
        `- **${project.name} - Server license:** ${project.license.server.note} ${link("Source reviewed", project.license.server.source)}.`,
      );
    }
    if (project.license.clients.note) {
      notes.push(
        `- **${project.name} - Client license:** ${project.license.clients.note} ${link("Source reviewed", project.license.clients.source)}.`,
      );
    }
    for (const column of featureColumns) {
      const entry = project.features[column.key]!;
      if (entry.note) {
        notes.push(
          `- **${project.name} - ${column.label}:** ${entry.note} ${link("Source reviewed", entry.source)}.`,
        );
      }
    }
    if (project.data_source.note) {
      notes.push(
        `- **${project.name} - Data source:** ${project.data_source.note} ${link("Source reviewed", project.data_source.source)}.`,
      );
    }
  }
  return notes;
}

function evidenceSets(projects: Project[]) {
  return projects
    .map((project) => {
      const dates = project.evidence_set
        .map((entry) => entry.verified_at)
        .toSorted();
      const reviewed =
        dates.at(0) === dates.at(-1)
          ? dates.at(0)
          : `${dates.at(0)} to ${dates.at(-1)}`;
      return `### ${project.name} - evidence reviewed ${reviewed}

${project.evidence_set
  .map(
    (entry) =>
      `- ${link(entry.label, entry.source)}: ${entry.scope}`,
  )
  .join("\n")}`;
    })
    .join("\n\n");
}

export function renderEvidence(data: ProjectData) {
  const active = activeProjects(data);
  const notes = evidenceNotes(active, data.comparison.feature_columns);

  return `<!-- Generated by scripts/generate-readme.ts from projects.yml. Do not edit by hand. -->

# Evidence for ${data.comparison.title}

Every comparison cell links to a public source. This document records the
complete evidence set reviewed for each active project and the notes behind
unknown cells.

[Back to the comparison](README.md)

## Reviewed evidence sets

Each set was declared before evaluating that project's cells. It includes the
repository README and the complete official documentation corpus available for
that project.

${evidenceSets(active)}

## Cell evidence notes

${notes.length > 0 ? notes.join("\n") : "No additional cell notes."}
`;
}
